name: deploy application
'on':
  push:
    branches:
      - docker-run-test-brach
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      -
        name: prepare the docker-compose run
        run: |
              ls -l
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: yanhang1/final-project-frontandback:latest
      -
        name: prepare the docker-compose run
        run: |
              mkdir 234-project
              cp docker-compose.yml final_project/docker-compose.yml
              cd 234-project
              docker-compose -H ${{ secrets.HOST_SERVER  }} down
              docker-compose -H ${{ secrets.HOST_SERVER  }} pull
              docker-compose -H ${{ secrets.HOST_SERVER  }} up -d